name = "webwaka-logistics"
main = "server/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "webwaka-logistics-db"
database_id = "NEEDS_D1_UPGRADE"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "ef463888d10e487ba4fe3563f7f71964"

[[kv_namespaces]]
binding = "EVENTS"
id = "2fc767bf19f848119d347aa90ca23fe4"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "webwaka-logistics-storage"
